import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

//export const metadata: Metadata = {
// title: "Create Next App",
//  description: "Generated by create next app",
//};

export const metadata: Metadata = {
  metadataBase: new URL("https://melissa-x-constantine.vercel.app"),
  title: "Melissa & Constantine",
  description: "Save the date — March 29, 2026 · Beacon, NY",
  openGraph: {
    title: "Melissa & Constantine",
    description: "Save the date — March 29, 2026 · Beacon, NY",
    url: "/",
    siteName: "Melissa & Constantine",
    images: [
      {
        // safer if you rename file to Melissa-and-Constantine.png
        url: "/images/Melissa%26Constantine.png",
        width: 1200,
        height: 630,
        alt: "Melissa & Constantine",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Melissa & Constantine",
    description: "Save the date — March 29, 2026 · Beacon, NY",
    images: ["/images/Melissa%26Constantine.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
